
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPLUSMINUSleftMULTIPLYDIVIDECOMMA DIVIDE EQUALS FLOAT INT LRB MINUS MULTIPLY NAME PLUS PRINT RRB SEMICOLON STRING\n    calc : expression\n        | var_assign\n        | empty\n    \n    var_assign : NAME EQUALS expression\n    \n    expression : expression MULTIPLY expression\n                | expression DIVIDE expression \n                | expression PLUS expression\n                | expression MINUS expression\n\n    \n    expression : INT\n              | FLOAT\n              | STRING\n    \n    expression : NAME\n    \n    empty : \n\n    '
    
_lr_action_items = {'INT':([0,9,10,11,12,13,],[5,5,5,5,5,5,]),'FLOAT':([0,9,10,11,12,13,],[6,6,6,6,6,6,]),'STRING':([0,9,10,11,12,13,],[7,7,7,7,7,7,]),'NAME':([0,9,10,11,12,13,],[8,15,15,15,15,15,]),'$end':([0,1,2,3,4,5,6,7,8,14,15,16,17,18,19,],[-13,0,-1,-2,-3,-9,-10,-11,-12,-5,-12,-6,-7,-8,-4,]),'MULTIPLY':([2,5,6,7,8,14,15,16,17,18,19,],[9,-9,-10,-11,-12,-5,-12,-6,9,9,9,]),'DIVIDE':([2,5,6,7,8,14,15,16,17,18,19,],[10,-9,-10,-11,-12,-5,-12,-6,10,10,10,]),'PLUS':([2,5,6,7,8,14,15,16,17,18,19,],[11,-9,-10,-11,-12,-5,-12,-6,-7,-8,11,]),'MINUS':([2,5,6,7,8,14,15,16,17,18,19,],[12,-9,-10,-11,-12,-5,-12,-6,-7,-8,12,]),'EQUALS':([8,],[13,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'calc':([0,],[1,]),'expression':([0,9,10,11,12,13,],[2,14,16,17,18,19,]),'var_assign':([0,],[3,]),'empty':([0,],[4,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> calc","S'",1,None,None,None),
  ('calc -> expression','calc',1,'p_calc','myParser.py',13),
  ('calc -> var_assign','calc',1,'p_calc','myParser.py',14),
  ('calc -> empty','calc',1,'p_calc','myParser.py',15),
  ('var_assign -> NAME EQUALS expression','var_assign',3,'p_var_assign','myParser.py',23),
  ('expression -> expression MULTIPLY expression','expression',3,'p_expression','myParser.py',30),
  ('expression -> expression DIVIDE expression','expression',3,'p_expression','myParser.py',31),
  ('expression -> expression PLUS expression','expression',3,'p_expression','myParser.py',32),
  ('expression -> expression MINUS expression','expression',3,'p_expression','myParser.py',33),
  ('expression -> INT','expression',1,'p_expression_int_float_string','myParser.py',41),
  ('expression -> FLOAT','expression',1,'p_expression_int_float_string','myParser.py',42),
  ('expression -> STRING','expression',1,'p_expression_int_float_string','myParser.py',43),
  ('expression -> NAME','expression',1,'p_expression_var','myParser.py',50),
  ('empty -> <empty>','empty',0,'p_empty','myParser.py',57),
]
